### ISSUE TITLE
Address not sent in the payload 

### ISSUE THREAD

**Issue by Aaronmyster** [itransact/itransact-node#2]
There's an address model, but it doesn't seem to be sent in the payload.
We're getting back an exception: "ZIP REQUIRED FOR KEYED TRANSACTION", but we're not able to pass any address data.

**Comment by Aaronmyster** [comment]
https://github.com/itransact/itransact-node/issues/2

**Comment by xavisavvy** [comment]
Hey @Aaronmyster~ 

Thanks for taking the time to let us know!

I will look into this and let you know what I found out. I know we just deployed some new enhancements so this might be related. I will update you here once I have a bead on it.

**Comment by xavisavvy** [comment]
@Aaronmyster If its a sandbox / loopback / demo account then this error is coming back from the processor, normally the zip is not required only on those demo accounts. 

Do you know if you are using a sandbox / loopback / demo account? 

I am checking a few other avenues in the meantime~

**Comment by xavisavvy** [comment]
Just published a change for 1.0.2 - this should include the address on the payload object (that way if you are using a Loopback / Sandbox / Demo account it should go through.) Normally it should not be required. Let me know if it gives you and issues~

**Comment by Aaronmyster** [comment]
Thanks for the quick response! Seems to be working!

**Comment by xavisavvy** [comment]
Anytime! Let us know if you have any more questions~
